### PR TITLE
feat(optional): add support to map from optional to required property

### PR DESCRIPTION
**Pull request by jakubtrzcinski**
**This is early version of the PR, i'd really enjoy feedback from you!**

**Api Changes:**
* added optional defaultValue property in @Mapping annotation.  (No breaking changes)

**Current state:**
Added support for mapping from optional to required property, if source value is null, defaultValue will be used, otherwise mapping will fail.

**Previous State:**
If tired to map from optional to required it generates uncompilable code

Example:
```dart
@Mapper
abstract class NullablePropertiesMapper {
  @Mapping(source: 'number', target: 'number', defaultValue: '0')
  NullablePropertiesTarget fromSource(NullablePropertiesSource source);
}
```

will produce:

```dart
class NullablePropertiesMapperImpl extends NullablePropertiesMapper {
  NullablePropertiesMapperImpl() : super();

  @override
  NullablePropertiesTarget fromSource(NullablePropertiesSource source) {
    assert(source.text != null, 'text cannot be blank');
    final nullablepropertiestarget =
        NullablePropertiesTarget(source.text!, source.number ?? 0);
    return nullablepropertiestarget;
  }
}
```

### CODE REVIEW

**Comment by smotastic** [comment]
Hey I really like the idea of having this.
Code looks good on first look, but I'll make sure to check it out next week again.
In the meantime would you mind adding your example to the example.md located in example/README.md?

**Comment by jakubtrzcinski** [comment]
@smotastic sure will do!

i am also thinking about throwing dedicated exception eg. NullMappingException instead of having an assertion. what do you think about it?

**Comment by smotastic** [comment]
For your question if I would prefer an Exception or assert I wasn't that sure either.
But I like this answer here https://stackoverflow.com/a/17316538/9479695
So basically an assert is for when the developer did a mistake as in using the API wrong. 
An exception should be used, only when it is supposed to be handled by the caller.
If the Developer passes null for a certain attribute, he uses the API in a wrong way, so I like the usage of asserts here.

For the review, I noticed one small thing with the generation of the asserts.
As soon as I add a property in my Sourceclass which also has a setter, the generated asserts are doubled.

I extended your example to showcase this behaviour. Maybe you can have a look at it.
Also if the property is nullable and private, but the setter and getter return a non nullable property, we don't need the assert's for the private property.

```dart
import 'package:smartstruct/smartstruct.dart';

part 'nullable.mapper.g.dart';

class Foo {
  final String fooBar;
  final String fooBar2;
  final String someText;
  num? setterNumber;

  Foo(this.fooBar, this.fooBar2, this.someText, this.setterNumber);
}

class Bar {
  final String? fooBar;
  final String? fooBar2;

  String? _someText;
  num? _setterNumber;

  set someText(String someText) {
    _someText = someText;
  }

  String get someText {
    return _someText ?? '';
  }

  num? get setterNumber => _setterNumber;

  set setterNumber(num? setterNumber) {
    _setterNumber = setterNumber;
  }

  Bar(this.fooBar, this.fooBar2, this._someText, this._setterNumber);
}

/// Mapper showcasing mapping from optional to required field with defaultValue
@Mapper()
abstract class FooBarMapper {
  @Mapping(source: 'fooBar', target: 'fooBar', defaultValue: "''")
  Foo fromBar(Bar bar);
}
```

```dart
// generated mapper
class FooBarMapperImpl extends FooBarMapper {
  FooBarMapperImpl() : super();

  @override
  Foo fromBar(Bar bar) {
    assert(bar.fooBar2 != null, 'fooBar2 cannot be blank');
    assert(bar._someText != null, '_someText cannot be blank');
    assert(bar._someText != null, '_someText cannot be blank');
    assert(bar._setterNumber != null, '_setterNumber cannot be blank');
    assert(bar._setterNumber != null, '_setterNumber cannot be blank');
    assert(bar.setterNumber != null, 'setterNumber cannot be blank');
    assert(bar.setterNumber != null, 'setterNumber cannot be blank');
    final foo =
        Foo(bar.fooBar ?? '', bar.fooBar2!, bar.someText, bar.setterNumber);
    return foo;
  }
}
```

Sorry it took so long, but I'm in the middle of moving :D 
Hopefully next month I'll have some more time again, but I appreciate your contribution as I'm still trying to improve smartstruct in every way I can.

**Comment by jakubtrzcinski** [comment]
i will take a look on the reported issues tomorrow!

**Comment by smotastic** [comment]
Hi, I will close this PR for now due to inactivity.
But feel free to open another PR as soon as you find the time to do so.

**Pull request closed without merging**
